# Generated by Django 2.1 on 2018-08-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciopersona',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviciopersona',
            name='pago',
            field=models.FloatField(default=0),
        ),
    ]
